### ISSUE TITLE
Limit Stitched Receivers doesn't take effect unless Radio Model is changed

### ISSUE THREAD

**Issue by hharte** [TAPR/OpenHPSDR-PowerSDR#9]
I'm running the released version of OpenHPSDR mRX PS v3.3.15 with an ANAN-8000DLE and found an issue when disabling or re-enabling the "Limit Stitched Receivers" checkbox.  The setting does not take effect when the checkbox is toggled.  Applying settings doesn't help.  Powering off/on the radio does not help.  Quitting the application and restarting does not help.

The only way I found to resolve this issue is to change the Radio Model to something else, and then change it back.

**Comment by n6ctg** [comment]
Sounds very interesting.

**Comment by hharte** [comment]
This issue is resolved with the v3.3.16 release, thank you!
